### ISSUE TITLE
Thông báo mở Issue nhờ các bạn góp ý về đồ án!

### ISSUE THREAD

**Issue by huuthang2509** [huuthang2509/DoAn-CK---NMKHDL#2]
Hiện tại nhóm mình đã hoàn thành phần cào dữ liệu, tiền xử lí dữ liệu (bao gồm cả xây pipeline), thử chạy trên 1 model.
Bọn mình đang thử nghiệm thêm nhiều model khác nhau nữa nhằm tìm ra model tốt nhất và sau đó sẽ tinh chỉnh lại code cho sạch sẽ và đẹp.
Mong các bạn góp ý thêm cho nhóm mình để nhóm mình có thể cải thiện những phần chưa được tốt!!

Cảm ơn các bạn nhìu :3

**Comment by grant-ward-101** [comment]
Bạn nên nêu rõ công dụng của class ColAdderDropper, vì mình thấy bạn xử lý khá nhiều mà mình ko nắm rõ được hết bạn muốn xử lý thế nào với các cột dữ liệu

**Comment by bason1999qn** [comment]
Chào các bạn, mình là Sơn đến từ nhóm 45.
Mình có chút góp ý về thấy phần đánh giá mô hình, các bạn chưa đưa ra nhận xét và giải thích về mô hình?  

Chúc các bạn sớm hoàn thành đồ án và thuận lợi trong quá trình vấn đáp ✌️

**Comment by huuthang2509** [comment]
Cảm ơn góp ý của 2 bạn rất nhiều. Mình sẽ cố gắng bổ sung thêm các ý cần thiết.

Chúc các bạn vấn đáp thuận lợi 💯
